apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: packet-loss-SERVICE_PLACEHOLDER
  namespace: default
spec:
  action: loss
  mode: all
  selector:
    labelSelectors:
      app: SERVICE_PLACEHOLDER
  loss:
    loss: '45'
    correlation: '100'
  duration: '60s'
